# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Pouyan Nahed
title: Software Engineer
email: pouyan9675@gmail.com
# phone: Your phone number (optional)
# website: Your website (eg. https://google.com)(optional)

# Social links
twitter_username: i_am_pouyan
github_username:  pouyan9675
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: pouyan.na
linkedin_username: pouyan-n-508a4586
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/pouyan.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a 23 years old Ph.D. student in Computer Computer Science at the [Department of Computer Science](https://www.unlv.edu/cs) of [University of Nevada, Las Vegas](https://www.unlv.edu/). I love <mark>Natural Language Processing</mark> and <mark>Deep Learning</mark>. To be more specific, I am enthusiastic about language models and generating ChatBots using deep models. I was Software Engineer and Android Programmer at [BlackBoard](http://black-boards.ir/).
  Beside, I have advanced skill and 5 years experience of <mark>Android</mark> application programming and I have developed many applications which are available through markets.

  I never get tired of learning new things and challenging myself.
  My skills are as the following list
    - Java
    - Python
    - Android
    - Deep Learning
    - Natural Language Processing
    - Lots of graphic software and etc. 

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# educaton_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  I am really interested in **teamworks** and I have exprienced in *leading* minor teams. In freetimes I consider to learn new things and updating my knowledge about technology and all other stuffs.
  I have other relevant skills to computer science either such as
  - Django
  - Adobe XD
  - Adobe Photoshop
  - Adobe Lightroom

  Furthermore, my chief interests are *music*, online computer games especially *Fortnite* ;) , *photography*, reading *books* and watching *movies*.

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
